# Generated by Django 6.1.1 on 2026-10-01 07:34

from django.db import migrations

# categories, tags, and products to be seeded
categories_data = [ 'Electronics', 'Clothing', 'Books' ]
tags_data = [ 'New', 'Sale', 'Popular' ]
products_data = [
    {
        'name': 'Smartphone',
        'description': 'A high-end smartphone with a great camera.',
        'price': 699.99,
        'category': 'Electronics',
        'tags': ['New', 'Popular']
    },
    {
        'name': 'T-Shirt',
        'description': 'A comfortable cotton t-shirt.',
        'price': 19.99,
        'category': 'Clothing',
        'tags': ['Sale']
    },
    {
        'name': 'Novel',
        'description': 'An engaging fiction novel.',
        'price': 14.99,
        'category': 'Books',
        'tags': []
    }
]

def seed_sample_data(apps, schema_editor):
    Category = apps.get_model('products', 'Category')
    Tag = apps.get_model('products', 'Tag')
    Product = apps.get_model('products', 'Product')

    # Create sample categories
    categories = {}
    for category in categories_data:
        categories[category] = Category.objects.create(name=category)

    # Create sample tags
    tags = {}
    for tag in tags_data:
        tags[tag] = Tag.objects.create(name=tag)

    # Create sample products
    for product in products_data:
        product_obj = Product.objects.create(
            name=product['name'],
            description=product['description'],
            price=product['price'],
            category=categories[product['category']]
        )
        # Add tags to the product
        for tag_name in product['tags']:
            product_obj.tags.add(tags[tag_name])

def reverse_seed_sample_data(apps, schema_editor):
    Category = apps.get_model('products', 'Category')
    Tag = apps.get_model('products', 'Tag')
    Product = apps.get_model('products', 'Product')

    # Delete the above seeded products, tags, and categories
    Product.objects.filter(
        name__in=[
            products_data[i]['name'] for i in range(len(products_data))
        ]
    ).delete()

    # Prevent cascading deletion of products added later via Django admin
    for category in Category.objects.filter(name__in=categories_data):
        if not category.products.exists():
            category.delete()
    
    # Prevent cascading deletion of products added later via Django admin
    for tag in Tag.objects.filter(name__in=tags_data):
        if not tag.products.exists():
            tag.delete()



class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_sample_data, reverse_code=reverse_seed_sample_data),
    ]
